version: '3.3'
services:

  todofront:
    build: ./todo-app/front-end
    ports:
      - 3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001

  todotests:
    build: ./todo-app/tests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront